<?php
// count 142
$languages_list = array(
    array("name" => "Afrikaans", "code" => "af"),
    array("name" => "Albanian - shqip", "code" => "sq"),
    array("name" => "Amharic - ????", "code" => "am"),
    array("name" => "Arabic - ???????", "code" => "ar"),
    array("name" => "Aragonese - aragonés", "code" => "an"),
    array("name" => "Armenian - ???????", "code" => "hy"),
    array("name" => "Asturian - asturianu", "code" => "ast"),
    array("name" => "Azerbaijani - az?rbaycan dili", "code" => "az"),
    array("name" => "Basque - euskara", "code" => "eu"),
    array("name" => "Belarusian - ??????????", "code" => "be"),
    array("name" => "Bengali - ?????", "code" => "bn"),
    array("name" => "Bosnian - bosanski", "code" => "bs"),
    array("name" => "Breton - brezhoneg", "code" => "br"),
    array("name" => "Bulgarian - ?????????", "code" => "bg"),
    array("name" => "Catalan - català", "code" => "ca"),
    array("name" => "Central Kurdish - ????? (???????? ??????)", "code" => "ckb"),
    array("name" => "Chinese - ??", "code" => "zh"),
    array("name" => "Chinese (Hong Kong) - ??(??)", "code" => "zh-HK"),
    array("name" => "Chinese (Simplified) - ??(??)", "code" => "zh-CN"),
    array("name" => "Chinese (Traditional) - ??(??)", "code" => "zh-TW"),
    array("name" => "Corsican", "code" => "co"),
    array("name" => "Croatian - hrvatski", "code" => "hr"),
    array("name" => "Czech - ceština", "code" => "cs"),
    array("name" => "Danish - dansk", "code" => "da"),
    array("name" => "Dutch - Nederlands", "code" => "nl"),
    array("name" => "English", "code" => "en"),
    array("name" => "English (Australia)", "code" => "en-AU"),
    array("name" => "English (Canada)", "code" => "en-CA"),
    array("name" => "English (India)", "code" => "en-IN"),
    array("name" => "English (New Zealand)", "code" => "en-NZ"),
    array("name" => "English (South Africa)", "code" => "en-ZA"),
    array("name" => "English (United Kingdom)", "code" => "en-GB"),
    array("name" => "English (United States)", "code" => "en-US"),
    array("name" => "Esperanto - esperanto", "code" => "eo"),
    array("name" => "Estonian - eesti", "code" => "et"),
    array("name" => "Faroese - føroyskt", "code" => "fo"),
    array("name" => "Filipino", "code" => "fil"),
    array("name" => "Finnish - suomi", "code" => "fi"),
    array("name" => "French - français", "code" => "fr"),
    array("name" => "French (Canada) - français (Canada)", "code" => "fr-CA"),
    array("name" => "French (France) - français (France)", "code" => "fr-FR"),
    array("name" => "French (Switzerland) - français (Suisse)", "code" => "fr-CH"),
    array("name" => "Galician - galego", "code" => "gl"),
    array("name" => "Georgian - ???????", "code" => "ka"),
    array("name" => "German - Deutsch", "code" => "de"),
    array("name" => "German (Austria) - Deutsch (Österreich)", "code" => "de-AT"),
    array("name" => "German (Germany) - Deutsch (Deutschland)", "code" => "de-DE"),
    array("name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "code" => "de-LI"),
    array("name" => "German (Switzerland) - Deutsch (Schweiz)", "code" => "de-CH"),
    array("name" => "Greek - ????????", "code" => "el"),
    array("name" => "Guarani", "code" => "gn"),
    array("name" => "Gujarati - ???????", "code" => "gu"),
    array("name" => "Hausa", "code" => "ha"),
    array("name" => "Hawaiian - ?Olelo Hawai?i", "code" => "haw"),
    array("name" => "Hebrew - ?????", "code" => "he"),
    array("name" => "Hindi - ??????", "code" => "hi"),
    array("name" => "Hungarian - magyar", "code" => "hu"),
    array("name" => "Icelandic - íslenska", "code" => "is"),
    array("name" => "Indonesian - Indonesia", "code" => "id"),
    array("name" => "Interlingua", "code" => "ia"),
    array("name" => "Irish - Gaeilge", "code" => "ga"),
    array("name" => "Italian - italiano", "code" => "it"),
    array("name" => "Italian (Italy) - italiano (Italia)", "code" => "it-IT"),
    array("name" => "Italian (Switzerland) - italiano (Svizzera)", "code" => "it-CH"),
    array("name" => "Japanese - ???", "code" => "ja"),
    array("name" => "Kannada - ?????", "code" => "kn"),
    array("name" => "Kazakh - ????? ????", "code" => "kk"),
    array("name" => "Khmer - ?????", "code" => "km"),
    array("name" => "Korean - ???", "code" => "ko"),
    array("name" => "Kurdish - Kurdî", "code" => "ku"),
    array("name" => "Kyrgyz - ????????", "code" => "ky"),
    array("name" => "Lao - ???", "code" => "lo"),
    array("name" => "Latin", "code" => "la"),
    array("name" => "Latvian - latviešu", "code" => "lv"),
    array("name" => "Lingala - lingála", "code" => "ln"),
    array("name" => "Lithuanian - lietuviu", "code" => "lt"),
    array("name" => "Macedonian - ??????????", "code" => "mk"),
    array("name" => "Malay - Bahasa Melayu", "code" => "ms"),
    array("name" => "Malayalam - ??????", "code" => "ml"),
    array("name" => "Maltese - Malti", "code" => "mt"),
    array("name" => "Marathi - ?????", "code" => "mr"),
    array("name" => "Mongolian - ??????", "code" => "mn"),
    array("name" => "Nepali - ??????", "code" => "ne"),
    array("name" => "Norwegian - norsk", "code" => "no"),
    array("name" => "Norwegian Bokmål - norsk bokmål", "code" => "nb"),
    array("name" => "Norwegian Nynorsk - nynorsk", "code" => "nn"),
    array("name" => "Occitan", "code" => "oc"),
    array("name" => "Oriya - ?????", "code" => "or"),
    array("name" => "Oromo - Oromoo", "code" => "om"),
    array("name" => "Pashto - ????", "code" => "ps"),
    array("name" => "Persian - ?????", "code" => "fa"),
    array("name" => "Polish - polski", "code" => "pl"),
    array("name" => "Portuguese - português", "code" => "pt"),
    array("name" => "Portuguese (Brazil) - português (Brasil)", "code" => "pt-BR"),
    array("name" => "Portuguese (Portugal) - português (Portugal)", "code" => "pt-PT"),
    array("name" => "Punjabi - ??????", "code" => "pa"),
    array("name" => "Quechua", "code" => "qu"),
    array("name" => "Romanian - româna", "code" => "ro"),
    array("name" => "Romanian (Moldova) - româna (Moldova)", "code" => "mo"),
    array("name" => "Romansh - rumantsch", "code" => "rm"),
    array("name" => "Russian - ???????", "code" => "ru"),
    array("name" => "Scottish Gaelic", "code" => "gd"),
    array("name" => "Serbian - ??????", "code" => "sr"),
    array("name" => "Serbo - Croatian", "code" => "sh"),
    array("name" => "Shona - chiShona", "code" => "sn"),
    array("name" => "Sindhi", "code" => "sd"),
    array("name" => "Sinhala - ?????", "code" => "si"),
    array("name" => "Slovak - slovencina", "code" => "sk"),
    array("name" => "Slovenian - slovenšcina", "code" => "sl"),
    array("name" => "Somali - Soomaali", "code" => "so"),
    array("name" => "Southern Sotho", "code" => "st"),
    array("name" => "Spanish - español", "code" => "es"),
    array("name" => "Spanish (Argentina) - español (Argentina)", "code" => "es-AR"),
    array("name" => "Spanish (Latin America) - español (Latinoamérica)", "code" => "es-419"),
    array("name" => "Spanish (Mexico) - español (México)", "code" => "es-MX"),
    array("name" => "Spanish (Spain) - español (España)", "code" => "es-ES"),
    array("name" => "Spanish (United States) - español (Estados Unidos)", "code" => "es-US"),
    array("name" => "Sundanese", "code" => "su"),
    array("name" => "Swahili - Kiswahili", "code" => "sw"),
    array("name" => "Swedish - svenska", "code" => "sv"),
    array("name" => "Tajik - ??????", "code" => "tg"),
    array("name" => "Tamil - ?????", "code" => "ta"),
    array("name" => "Tatar", "code" => "tt"),
    array("name" => "Telugu - ??????", "code" => "te"),
    array("name" => "Thai - ???", "code" => "th"),
    array("name" => "Tigrinya - ????", "code" => "ti"),
    array("name" => "Tongan - lea fakatonga", "code" => "to"),
    array("name" => "Turkish - Türkçe", "code" => "tr"),
    array("name" => "Turkmen", "code" => "tk"),
    array("name" => "Twi", "code" => "tw"),
    array("name" => "Ukrainian - ??????????", "code" => "uk"),
    array("name" => "Urdu - ????", "code" => "ur"),
    array("name" => "Uyghur", "code" => "ug"),
    array("name" => "Uzbek - o‘zbek", "code" => "uz"),
    array("name" => "Vietnamese - Ti?ng Vi?t", "code" => "vi"),
    array("name" => "Walloon - wa", "code" => "wa"),
    array("name" => "Welsh - Cymraeg", "code" => "cy"),
    array("name" => "Western Frisian", "code" => "fy"),
    array("name" => "Xhosa", "code" => "xh"),
    array("name" => "Yiddish", "code" => "yi"),
    array("name" => "Yoruba - Èdè Yorùbá", "code" => "yo"),
    array("name" => "Zulu - isiZulu", "code" => "zu")
)
?>